#!/usr/bin/env node

var exec = require('child_process').exec;

var usage = "git-push 'path/to/file1 folder2 file3' 'commit message' <origin> <branch>";
//var user = run('git config user.name', { silent: true });

function run(command, callback) {
    console.log('Running '+command+'...');
    var run = exec(command, function(err, stdout, stderr) {
        if (err) return console.log(err+'\nUSAGE: "'+usage+'"');
        console.log(stdout);
        if (callback) callback();
    });
}

if (process.argv.length !== 6) return console.log('USAGE: "'+usage+'"');

run('git add "'+process.argv[2]+'"', () => { run('git commit -m "'+process.argv[3]+'"', () => { run('git push '+process.argv[4]+' '+process.argv[5]) }) })
