#!/usr/bin/env node

var exec = require('child_process').exec;

var usage = "git-clone local-repo.git";
var user = run('git config user.name', { silent: true });


function run(command, callback) {
    if (!callback) callback = { silent: false };
    var response = '';

    console.log('Running '+command+'...');
    var run = exec(command, function(err, stdout, stderr) {
        if (err) return console.log(err+'\nUSAGE: "'+usage+'"');
        if (!callback.silent) console.log(stdout);
        response = stdout;
    });
    run.on('exit', function (code) {
        if (!callback.silent) console.log(code);
        if (callback && !callback.silent) callback();
    });
    return response;
}

var wrongLength = process.argv.length !== 3;
if (prcoess.argv.length !== 3) return console.log('USAGE: "'+usage+'"');

run('git clone https://github.com/'+user+'/'+process.argv[3]);
