#!/usr/bin/env node

var exec = require('child_process').exec;

var usage = "git-clone local-repo.git";
var user;

function run(command, callback) {
    var getUser = command.includes('git config user.name');

    console.log('Running '+command+'...');
    var run = exec(command, function(err, stdout, stderr) {
        if (getUser) user = stdout.replace(/(\r\n|\n|\r)/gm,"");

        if (err) return console.log(err+'\nUSAGE: "'+usage+'"');
        if (!getUser) console.log(stdout);
        if (callback) callback();
    });
}

var wrongLength = process.argv.length !== 3;
if (process.argv.length !== 3) return console.log('USAGE: "'+usage+'"');

run('git config user.name', () => { run('git clone https://github.com/'+user+'/'+process.argv[2]) });
